sudo: required
os: linux
language: minimal
addons:
  apt:
    packages:
    - docker-ce
git:
  depth: 4
services:
  - docker

before_install:
  - docker pull debian:stable-slim

script:
  - docker version
  - docker build --no-cache --tag lacledeslan/gamesvr-quake2 --build-arg BUILDNODE=TravisCI --build-arg SOURCE_COMMIT="$TRAVIS_COMMIT" -f linux.Dockerfile .
  - docker run -it --rm lacledeslan/gamesvr-quake2 ./ll-tests/gamesvr-quake2.sh

notifications:
  slack:
    secure: RQVPrbAGIkjWPZI0qKUHIoJzvWUk8oFyJ5RTRCXigRQRuJUlW1sfQonXCsbi1K9n04sg5yhgdLTs9p5PjS282CQQ7jq1Cjq+KY7pxAyrD1m9/YUBIe71qSTOGlLKpjqt6x1iqk6HKfzO3f7HbBnLP4WmBFrAeUFMLSdopJGcrAlGcQX699SmWE4Khg89fR/vRvb4ovEKMDbZ2wvYD/kGtQJDFAf4DWqkg3o0Z14vikz/Qzn+zauC4KdhK8N2reqwqjMNc4Ifmf2YpCr86n25t1DxmSLAkSXrffa7FCwlYfjOW74uBraCeVCnGYdqCzrPD+EB0HvkrI2S+X0sFQZpUR4/ld0/4n7LucGT5432ELbCGQ2A4SRxh35EEC5Q6ti/xgOT7hs88ocPDfz5UOlboh1q9AUb5FpIy4TJ5f2pxcSN53J6AvFcMj1eTDosl981dmDSlP4rH6CfK6yGgiWvix8UnA2IwPW8t4wJAzwT/8QXXlI8xw0IOkzKinvF6/aShXNYICJ1YcBm1ndeyo6um8p2eMLKlooE2xmnlUGNNRdpPvg0va0FtOCJRmAr/HxpHmUCawYPIpOBFAsK+1K82LbHfgHfPorFTM8UsNqf8Jw2bO9viK8S9fEx66tbOwkYrhG3fTaBThuUEHqZ85Iu+xty5iw2QzaXdVZJxHI0NQg=

before_deploy:
  - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin;
deploy:
  provider: script
  script: docker push lacledeslan/gamesvr-quake2
  on:
    branch: master

after_deploy:
 - curl -X POST https://hooks.microbadger.com/images/lacledeslan/gamesvr-cssource/$MICROBADGER_TOKEN
